name: brij_client_example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brij_client:
    path: ../
  cross_file: ^0.3.4+1
  cryptography: ^2.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  solana: ^0.31.0
  uuid: ^4.5.1

dev_dependencies:
  mews_pedantic: ^0.28.0

flutter:
  uses-material-design: true
