name: brij_client
version: 1.0.10
description: A sample command-line application.

environment:
  sdk: ^3.7.0

dependencies:
  brij_protos_dart:
    git:
      url: https://github.com/espresso-cash/protos.git
      ref: v0.23.0
      path: brij_protos_dart
  bs58: ^1.0.2
  connectrpc: ^0.4.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^2.14.0
  dfunc: ^0.10.0
  freezed_annotation: ^2.4.1
  pinenacl: ^0.6.0
  protobuf: ^4.1.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  mews_pedantic: ^0.31.1
