name: kyc_client_dart
version: 1.0.0
description: A sample command-line application.

environment:
  sdk: ^3.4.3

dependencies:
  bs58: ^1.0.2
  convert: ^3.1.1
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^2.14.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  pinenacl: ^0.6.0
  protobuf: ^3.1.0
  retrofit: ^4.0.3
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mews_pedantic: ^0.31.1
  retrofit_generator: ^8.0.6
  swagger_parser: ^1.18.1

swagger_parser:
  output_directory: lib/src/api
  squash_clients: false
  merge_clients: false

  schemes:
    - schema_path: schemes/validator.json
      json_serializer: freezed
      root_client: false
      put_in_folder: true
      put_clients_in_folder: true

    - schema_path: schemes/kyc.json
      json_serializer: freezed
      root_client: false
      put_in_folder: true
      put_clients_in_folder: true